### PR TITLE
feature:add k3priorityqueue

### PR DESCRIPTION
**Pull request by IloveKanade**
The priorityqueue module has been modified according to the specification

### CODE REVIEW

**Comment by drmingdrmer** [comment]
Hm...it seems flake8 fails the lint check of `_building/tmpl`.
I did not yet found this. 
The flake script should be updated.

**Comment by IloveKanade** [comment]
> Hm...it seems flake8 fails the lint check of `_building/tmpl`.
> I did not yet found this.
> The flake script should be updated.

So do I need to remove TML or ignore lint for now?

**Comment by drmingdrmer** [comment]
> So do I need to remove TML or ignore lint for now?

I'd push a PR to fix this issue to make sure future package won't has this problem.
Then you can rebase to the fixed master.

**Comment by drmingdrmer** [comment]
I've done fixing the flake8 issue.
You could keep the _building/tmpl as is from now on.

**Comment by drmingdrmer** [comment]
@IloveKanade you'd need to rebase to the upstream master to have the patch included in your PR.

**Comment by IloveKanade** [comment]
> @IloveKanade you'd need to rebase to the upstream master to have the patch included in your PR.

hmmm.... It seems that the problem is not completely resolved and that tml will not pass pyTest compilation

**Review by drmingdrmer — APPROVED** [review]

**Review by pengsven — APPROVED** [review]

**Pull request merged**
